spring:
  application:
    name: jianyi-eureka
  profiles:
    active: eureka7001

---
spring:
  profiles: eureka7001
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001 # eureka 服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册
    fetch-registry: false # false 表示自己端是注册中心，我的职责就是维护服务实例，并不要去检索服务
    service-url:
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/ # 设置与Eureka Server 交互的地址查询服务和注册服务

---
spring:
  profiles: eureka7002

server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002 # eureka 服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册
    fetch-registry: false # false 表示自己端是注册中心，我的职责就是维护服务实例，并不要去检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/ # 设置与Eureka Server 交互的地址查询服务和注册服务

---
spring:
  profiles: eureka7003

server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003 # eureka 服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册
    fetch-registry: false # false 表示自己端是注册中心，我的职责就是维护服务实例，并不要去检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/ # 设置与Eureka Server 交互的地址查询服务和注册服务
